version: '3'
services:
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    shm_size: '2g'
    networks:
      - selenium-network
    volumes:
      - ./tests:/mnt/tests  # Монтируем папку с тестами в контейнер
      - ./requirements.txt:/mnt/requirements.txt  # Монтируем requirements.txt

networks:
  selenium-network:
    driver: bridge
